version: '3'  # Specify the Docker Compose version

services:
  adguardhome:  # Define the service named 'adguardhome'
    image: adguard/adguardhome  # Use the 'adguard/adguardhome' Docker image
    container_name: adguardhome-dot  # Set the container name to 'adguardhome'
    restart: unless-stopped  # Restart the container automatically unless stopped manually
    ports:  # Map container ports to host ports
      # Expose port 53 on TCP and UDP for DNS queries
      - "172.16.172.14:53:53/tcp"
      - "172.16.172.14:53:53/udp"

      # Expose port 67 on UDP for DHCP server
      - "172.16.172.14:67:67/udp"

      # Expose port 68 on UDP for DHCP client
      # - "172.16.172.14:68:68/udp"

      # Expose port 80 on TCP for HTTP web interface
      - "172.16.172.14:80:80/tcp"
      - "172.16.172.14:8888:8888/tcp"

      # Expose port 443 on TCP and UDP for HTTPS web interface
      - "172.16.172.14:443:443/tcp"
      - "172.16.172.14:443:443/udp"

      # Expose port 3000 on TCP for AdGuard Home's API
      - "172.16.172.14:3000:3000/tcp"

      # Expose port 853 on TCP for DNS-over-TLS (DoT)
      - "172.16.172.14:853:853/tcp"

      # Expose port 784 on UDP for DNS-over-QUIC (DoQ)
      - "172.16.172.14:784:784/udp"

      # Expose port 853 on UDP for DNS-over-DTLS (DoT)
      - "172.16.172.14:853:853/udp"

      # Expose port 8853 on UDP for DNS-over-TLS (DoT)
      - "172.16.172.14:8853:8853/udp"

      # Expose port 5443 on TCP and UDP for DNSCrypt
      - "172.16.172.14:5443:5443/tcp"
      - "172.16.172.14:5443:5443/udp"
    volumes:  # Mount host directories as volumes inside the container
      - /volume1/data/adguard-home/work:/opt/adguardhome/work  # Mount '/my/own/workdir' to '/opt/adguardhome/work'
      - /volume1/data/adguard-home/confdir:/opt/adguardhome/conf  # Mount '/my/own/confdir' to '/opt/adguardhome/conf'
